Assignment 1
shaurya-src/nuclei-assignments pull request #1
Opened 2022-01-06 16:53 UTC by shaurya-src

2022-01-07 10:31 UTC, shaurya-src commented on Assignment-1/bin/brute2.dart
> +    // ############################################
f

2022-01-07 11:23 UTC, Akanksha-nuclei requested changes

2022-01-07 11:51 UTC, shaurya-src commented on Assignment-1/bin/brute2.dart
> +void main() {
Moved main function to main.dart (and kept the Item class in item.dart file).

2022-01-07 11:52 UTC, shaurya-src commented on Assignment-1/bin/brute2.dart
> +
Implemented enum to validate item type.

2022-01-07 11:52 UTC, shaurya-src commented on Assignment-1/bin/brute2.dart
> +
Implemented enum to validate item type.

2022-01-07 11:54 UTC, shaurya-src commented on Assignment-1/bin/brute2.dart
> +    try {
Done.

2022-01-07 11:58 UTC, shaurya-src commented on Assignment-1/bin/brute2.dart
> +    bool errorFlag = false;
![Error](https://user-images.githubusercontent.com/41169759/148540972-dad1f15d-78c4-4731-beda-1a37cb5d5366.png)

If I don't initialize this, I'm getting this error

2022-01-07 12:22 UTC, shaurya-src commented on Assignment-1/bin/brute2.dart
> +    String itemName = stdin.readLineSync().toString();
Added checks for numeric and null values.

2022-01-07 12:40 UTC, shaurya-src commented on Assignment-1/bin/brute2.dart
> +        var surcharge;
Done

2022-01-07 15:10 UTC, Akanksha-nuclei commented on Assignment-1/lib/main.dart
> +
create a separate util class for this

2022-01-07 15:26 UTC, shaurya-src commented on Assignment-1/bin/brute2.dart
> +    bool errorFlag = false;
Made the changes!

2022-01-07 15:26 UTC, shaurya-src commented on Assignment-1/lib/main.dart
> +
Done. Made Util class in util.dart.

2022-01-08 20:39 UTC, Akanksha-nuclei commented on Assignment-1/lib/item.dart
> +
try to remove this variable and directly return from switch statement itself

2022-01-08 20:54 UTC, Akanksha-nuclei commented on Assignment-1/lib/item.dart
> +
these fields can be made final

2022-01-08 20:56 UTC, Akanksha-nuclei commented on Assignment-1/lib/item.dart
> +
check if you can make it a const constructor

2022-01-08 20:57 UTC, Akanksha-nuclei requested changes
changes requested

2022-01-10 08:36 UTC, Akanksha-nuclei commented on Assignment-1/lib/main.dart
> +
if name is not valid then person should not enter quantity

2022-01-13 10:05 UTC, closed without merging